Feat/#8 게임 데이터 배열화
ping-neo-meo-pong/pnmp pull request #9
Opened 2022-11-28 10:55 UTC by minsikim-42

서버에서 게임방 각각에 다른 정보를 보내줍니다.

2022-11-28 13:59 UTC, kimhxsong approved these changes

2022-11-28 14:02 UTC, kjh6b6a68 requested changes
생각해보니 eslint 를 적용시키지 않았네요... 제가 해놓은 부분에서 적용 안된 부분이 많아 죄송합니다... 머지 하기전에 eslint 적용을 먼저 하는게 좋을것 같아요

2022-11-28 14:06 UTC, Jiwon-Woo approved these changes
확인했습니다

2022-11-29 04:29 UTC, minsikim-42 commented
eslint 적용했습니다!

2022-11-29 04:30 UTC, merged